### PR TITLE
feat: added type hints for all methods

### LINKED ISSUE #82: Missing type annotations in public API and no available type stub
I was using the package and noticed that all type annotations were missing which made it a bit trickier to use this package OOTB instead of just importing and going for it.

I think all modern python projects should have type annotations to help with faster and safer development.

### PR DESCRIPTION
**Pull request by cn-ml**
I added type annotations to all public facing API methods as well as many internal functions and objects.
This raises a lot of helpful error messages using pyright, that can be used to detect possible programming mistakes.

Closes #82

### CODE REVIEW

**Comment by ajasmin** [comment]
This needs to have a `py.typed` file under `src/isodate` otherwise type checkers will treat the package as untyped.

**Comment by cn-ml** [comment]
> This needs to have a `py.typed` file under `src/isodate` otherwise type checkers will treat the package as untyped.

I'm not familiar with python packaging, did I do it correctly?

**Comment by ajasmin** [comment]
> > This needs to have a `py.typed` file under `src/isodate` otherwise type checkers will treat the package as untyped.
> 
> I'm not familiar with python packaging, did I do it correctly?

That looks correct.

I forked this branch to fix Python3.7 support if you'd like to merge this here:
https://github.com/cn-ml/isodate/pull/1

I'm not a maintainer on the project. I'm just trying to move this along.

**Comment by ajasmin** [comment]
I have another set of changes on top of this PR. See: https://github.com/cn-ml/isodate/pull/2

This further improves the type annotation and adds a passing `mypy --strict` check, which runs through pre-commit & GitHub workflow.

@cn-ml If you could have a look, and this still fulfills your use case, perhaps merge this here as well.

**Comment by gweis** [comment]
thanks, 

merged in https://github.com/gweis/isodate/commit/aa3a84d6e5b3cf4ecca2d0a2422766735336366d (plus a few other things)

**Pull request closed without merging**
